### ISSUE TITLE
New ABP file

### ISSUE THREAD

**Issue by caraMsmith** [zevross-spatial/rpackage-sensorDataImport#55]
We had to start using a new downloading software for the blood pressure monitor so now the blood pressure data file changed slightly preventing uploading. See email for new and old versions.

**Comment by zross** [comment]
This should be done, you will need to reinstall the package. Some things that changed:

1. "Unknown line" became "Unknown Line"
2. "Unknown line" used to occur twice and I used this to find the place where the file showed the number of valid lines. Now I use another approach.
3. The encoding is different (and more normal) in the current file.

**Comment by zross** [comment]
Close issue if you test and find that this is fixed.

**Comment by zross** [comment]
What version are you on? I just tried a fresh installation on 3.4 and it worked, I'll have Nate in my office try.

**Comment by zross** [comment]
I moved the issue about installation to a new issue #57

**Comment by caraMsmith** [comment]
Working now, thanks!

**Comment by caraMsmith** [comment]
Hi Zev, 

Apologies, but we now have to revert back to the old ABP files. I tried to edit the files to be like the ones that are currently able to upload, but had no luck. Would you be able to revert back to allow the upload of the old file type?

Thanks,
Cara

**Comment by zross** [comment]
I went back to the old one. Please pull and test.

**Comment by caraMsmith** [comment]
Thanks, I tested and is working now
