### ISSUE TITLE
GPX timestamp off

### ISSUE THREAD

**Issue by caraMsmith** [zevross-spatial/rpackage-sensorDataImport#56]
Timestamps on gps file is off. Timestamp appears to be 5 hours ahead. It seems to think it change to EST but really remained in UTC 
I have been fixing it on my own using this code:

#timestamps were off from database
gps_raw_y3$datetime2 <- ymd_hms(gps_raw_y3$datetime)
gps_raw_y3$datetime2 <- force_tz(gps_raw_y3$datetime2, tz="UTC")
attributes(gps_raw_y3$datetime2)$tzone <- "America/New_York"

**Comment by zross** [comment]
So to confirm what you want:

1. Raw data is in UTC
2. You want it in America/New York

![image](https://user-images.githubusercontent.com/1395177/40375132-ac4450d2-5db8-11e8-8009-de2b92728aba.png)

So if I apply the following code (I don't want to use lubridate since the package doesn't use it otherwise) then I get the values below is this what you want?:

```r
mutate(datetime = format(as.POSIXct(datetime, tz = "UTC"), tz = "America/New_York"))
$ datetime  <chr> "2013-07-09 08:39:57", "2013-07-09 08:39:58", "2013-07-09 08:39:59", "2013-07-09 ...
$ longitude <dbl> -73.96313, -73.96330, -73.96354, -73.96355, -73.96345, -73.96352, -73.96354, -73....
$ latitude  <dbl> 40.68769, 40.68768, 40.68766, 40.68773, 40.68781, 40.68784, 40.68781, 40.68780, 4...
$ elevation <chr> "14", "14", "19.5", "19.5", "19.3", "19.4", "19.4", "19.6", "19.6", "19.6", "19.6...
```

**Comment by zross** [comment]
I see issue #36 and I'm wondering if you could give a tiny bit more detail, I was misunderstanding. So it's in the database itself that the time is off right? And then when you bring it into R you make those manual changes? You're running this from NYC?

Are you able to open pgAdmin and run `show timezone;` (you'll need to connect to the db and open a query). I assume it's `US/Eastern`?

**Comment by zross** [comment]
OK, it should work now but how do you want to handle the fact that what you've uploaded before was UTC? From now on files uploaded will be in EST -- in the processing function I convert to EST from UTC.

**Comment by caraMsmith** [comment]
The gpx files will always be uploaded in UTC. What I did was exported the gpx files from the database, transferred them to my computer and changed the timestamp in R on my computer.

**Comment by caraMsmith** [comment]
Sorry for the confusing.  What we want is to upload the gpx files we download from Strava. See email I sent a few weeks ago for example files. The time stamp in these files is in UTC time. What we want is to upload all the files to the database and have the database automatically convert the time to New York time when it upload. Currently, it is only claiming to change the timestamp but not actually changing the time. When looking at the data in R, it said it is in New York timezone but is still 5 hours off (still in UTC). To fix this I ran the code in my initial comment on my own computer once I exported a csv file with all the gps data from the database computer. 

So, what we want is to convert it upon upload, and I think it is partially set up to do that as it is claiming to be in the correct timezone, but again the time itself isn't actually getting changed.

**Comment by zross** [comment]
This is a fairly quick change for me I believe. Here is the issue followed by a question:

1. Database is correctly set to Eastern time zone
2. GPS data is correctly set to UTC
3. The R script for loading data should (but does not yet) convert the data to Eastern before uploading.

I can implement a fix that converts the data to Eastern so that moving forward it should work fine. BUT your database right now has data in it already that has not been converted. I assume you need the existing data to be changed. I could give you SQL code to run from pgAdmin to change all the dates if you'd like and then we'd move forward with my fix. 

Does that work?

**Comment by caraMsmith** [comment]
Yes, that works well for me.

**Comment by zross** [comment]
OK to change the PostgreSQL database:

1. Have you done a backup? Data should be backed up.
2. Open pgAdmin, open a query window
3. Execute this line: **careful, how many hours do you want to add or subtract? Be sure to change as appropriate**

```sql
UPDATE gps SET datetime = datetime + interval '5h';
```

**Comment by zross** [comment]
The package has been altered to convert the time before uploading. See https://github.com/zevross-spatial/rpackage-sensorDataImport/blob/master/R/sensor_processing.R#L31

**Comment by caraMsmith** [comment]
The problem with using a code that only adjusts by 5 hours is some time are only off by 4 hours due to daylight savings. 

In the Update code in pgAdmin, is it possible to write a code such as the one I written previously (first comment). If not, it is actually not too big of a problem as in the future we will only extract data from 2018 (it was only 2017 data that was the problem and that data has already been adjusted and matched with other data)

**Comment by caraMsmith** [comment]
Great, a few things so I don't make a mistake.

1) Can you remind me how to backup the database. I remember doing it before and it wasn't too difficult, but confess I have since forgotten. 
2) Do the write that code in pgAdmin query window, or on the R console ?

**Comment by zross** [comment]
For backup look at the wiki: https://github.com/zevross-spatial/rpackage-sensorDataImport/wiki/Examples

That code should be executed in the R console. You may need to change the connection parameters?

**Comment by zross** [comment]
Did it ever work for you?

Short term let's do this the command line way. Might take a couple of back and forths if I have the parameters wrong here. But open Windows command line and try this command. You need to change the path to somewhere you'll be able to find preferably a path without a space in the name though I believe you can use quotes.

```bash
pg_dump --username postgres --port 5432 -- host localhost  -Fc columbiaBike > PATH/columbiaBike.dump
```

**Comment by caraMsmith** [comment]
We have backed it up before. 
I ran the command but got the following error:

pg_dump: too many command-line arguments (first is "localhost")

**Comment by zross** [comment]
Sorry there should not be a space before `host`. I've fixed it.

**Comment by caraMsmith** [comment]
Okay, got the backup to work. 

Went to run the code and got another error

> gps_raw_y3 <- dbGetQuery(con, "SELECT * FROM gps")
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘dbGetQuery’ for signature ‘"src_dbi", "character"’

**Comment by zross** [comment]
I changed the code above a bit, I'm wondering if you had any packages already loaded? Can you restart your R session (Session -> Restart R session in R Studio) then run the code above in that exact order see if you still get an error. If you get an error, run `sessionInfo()` and paste the results here.
