### ISSUE TITLE
Getting select data with get_sensor_data

### ISSUE THREAD

**Issue by caraMsmith** [zevross-spatial/rpackage-sensorDataImport#58]
Hi Zev, 

When using the code :
hex <- get_sensor_data("hxi",
                            do_aggregate     = TRUE,
                            aggregation_unit = "1 min",
                            xtravars         = NULL,
                            summarize_vars   = c("breathing_rate", "heart_rate", "minute_ventilation", "cadence"),
                            grouping_vars    = c("subjectid", "sessionid"))

is it possible add a line to only gather the data from a certain timeframe? The hexoskin files are very large and we don't need to keep calling data we have already gathered. 

Thanks,
Cara

**Comment by zross** [comment]
I added two arguments, `timestart` and `endstart`. These are datetimes, I wasn't sure if you wanted them to be dates only (I can do this if you'd prefer).

Does your actual code work? the "minute_ventilation" should be "minute_ventilation_adjusted" right?

Can you test the date time and make sure it works for you and does what you expect?

```r
get_sensor_data("hxi",
                do_aggregate = TRUE,
                aggregation_unit = "1 min",
                xtravars = NULL,
                summarize_vars = c("breathing_rate", 
                                   "heart_rate", 
                                   "minute_ventilation_adjusted", "cadence"),
                grouping_vars = c("subjectid", "sessionid"),
                timestart = "2017-07-27 06:45:00",
                timeend = "2017-07-27 06:45:08")
```

**Comment by caraMsmith** [comment]
Thank you, I tested and it is working well. And yes, the actual code used "minute_ventilation_adjusted" , I had just copied and pasted from an old code that was in the wiki examples in this site.
