### ISSUE TITLE
Database connection fail

### ISSUE THREAD

**Issue by caraMsmith** [zevross-spatial/rpackage-sensorDataImport#59]
Hi Zev, 

I started to do an upload and everything was going fine, but now there is an error saying "Error: argument is not interpretable as logical" and saying there is a problem with the database connection. When I open up pgAdmin it also says Connecting to database .... Failed

**Comment by zross** [comment]
Have you/did you try restarting the computer?

**Comment by caraMsmith** [comment]
Ah yes, the similar yet often most affective computer solution did the trick. Thanks
